name: Deploy

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🚀 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 🚀 Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: 🚧 Install and Build
        run: |
          pnpm install
          pnpm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          folder: dist
          clean: true
